import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/ToastProvider";
import { ReactElement } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bookify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactElement;
  params:{test:string}
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "bg-blue-100 h-[98vh] w-full"}>  
        <ToastProvider>
          {children}
        </ToastProvider>
        </body>
    </html>
  );
}