import Loading from "@/components/Loading";
import LogoutBTN from "@/components/LogoutBTN";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import { Suspense } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const navlinks = [
        {href:"/books",src:'/home.png', Name:"books"},
        {href:"/dashboard/address",src:'/location.png', Name:"Address"},
        {href:"/dashboard/orders",src:'/orders.png', Name:"Orders"},
        {href:"/dashboard/ebooks",src:'/ebook.png', Name:"Ebooks"},
    ]
    
  return (<>
    <div className="flex w-[100%] h-screen overflow-hidden">
        <div className=" relative flex flex-col  bg-clip-border rounded-xl bg-white text-gray-700 h-[calc(100vh)] w-full max-w-[20rem] p-4 shadow-xl shadow-blue-gray-900/5">
        <div className="mb-2 p-4">
            <h5 className="block antialiased tracking-normal font-sans text-xl font-semibold leading-snug text-gray-900">
            User Dashboard
            </h5>
        </div>
        <nav className="flex flex-col gap-1 min-w-[240px] p-2 font-sans text-base font-normal text-gray-700">
           {navlinks.map((e,i)=><Link
                role="button"
                tabIndex={0}
                href={e.href}
                key={i}
                className="flex items-center w-full p-3 rounded-lg text-start leading-tight transition-all hover:bg-blue-50 hover:bg-opacity-80 focus:bg-blue-50 focus:bg-opacity-80 active:bg-gray-50 active:bg-opacity-80 hover:text-blue-900 focus:text-blue-900 active:text-blue-900 outline-none">
                <div  className="grid place-items-center mr-4">
                <Image src={e.src} width={40} height={40} alt="home"/>
                </div>
                {e.Name}
            </Link>)}
            <div className="flex items-center w-full p-3 rounded-lg text-start leading-tight transition-all hover:bg-blue-50 hover:bg-opacity-80 focus:bg-blue-50 focus:bg-opacity-80 active:bg-gray-50 active:bg-opacity-80 hover:text-blue-900 focus:text-blue-900 active:text-blue-900 outline-none">
              <div  className="grid place-items-center mr-4">
              <Image src={"/logout.png"} width={40} height={40} alt="home"/>
              </div>
                <LogoutBTN />
            </div>
        </nav>
  </div>
    <div className="flex-grow min-h-screen overflow-scroll">
          {children}
    </div>

    </div>
</>);}
