import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links = {
    'home':'/',
    "books":"/books",
  }
  return (<>
        <Navbar links={links}/>
        <div className="w-full">
          <div className="h-[90vh] w-full">
            {children}
          </div>
        </div>
</>
  );}
